# EXAMPLE PASSWORD FILE. Copy to passwords.py and set appropriately

REDDIT_BOT_NAME = ''
REDDIT_CLIENT_ID = ''
REDDIT_CLIENT_SECRET = ''
REDDIT_BOT_USER_NAME = ''
REDDIT_USER_PASSWORD = ''

WIKI_BOT_NAME = ''
WIKI_BOT_LOGIN = ''
WIKI_BOT_PASSWORD = ''

DOK_API_KEY = ''

DISCORD_WEBHOOK = ''